Add BLS multisignatures
nspcc-dev/neofs-crypto pull request #2
Opened 2019-11-05 09:50 UTC by fyrchik

This PR implements interfaces for multisignatures and BLS as a default implementation.

2019-11-05 09:55 UTC, im-kulikov commented on multisig/multisig.go
> +	PublicKey  = kyber.Point
Add doc-comments for this types

2019-11-05 12:32 UTC, im-kulikov commented on multisig/multisig.go
> +func Verify(pub PublicKey, msg, sig []byte) error {
SignRFC6979 / Verify has different function signature.. mb we can change signature here, what you think?

2020-12-14 07:15 UTC, im-kulikov requested changes
rejected

2020-12-14 07:15 UTC, realloc commented
Not needed now

2020-12-14 07:15 UTC, closed without merging